version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements/dev.txt
      
      - run:
          name: run tests
          command: |
            source venv/bin/activate
            python -m pytest --cov . --cov-fail-under=90
      
      - run:
          name: run flake8
          command: |
            source venv/bin/activate
            flake8 --exclude venv --ignore E501
